version: "3.9"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    container_name: monitor_api_prod
    restart: unless-stopped
    networks:
      - monitor_net
    expose:
      - "8000"

  front:
    build:
      context: ./front
      dockerfile: Dockerfile.prod
      args:
        VITE_API_URL: "https://api.monitor.gautierchuinard.com"
    container_name: monitor_front_prod
    restart: unless-stopped
    networks:
      - monitor_net
    expose:
      - "80"

networks:
  monitor_net:
    name: monitor_net
    external: true
